### ISSUE TITLE
Anyone can use it?

### ISSUE THREAD

**Issue by ugintl** [eaudeweb/edw_modules#21]
Can anyone use this module?

**Comment by cristiroma** [comment]
Greetings @ugintl for the time being these modules are public, and there are no plans to make them private. Since the functionality is specific we've decided for the moment to not publish them on drupal.org and keep them here. It could be possible in the future we can move them to drupal.org.

Contributions are welcome!

**Comment by ugintl** [comment]
@cristiroma thank you. What was the purpose of this module when you developed it? What were you trying to achieve?
